export const METABALL_PARTICLES_COUNT_SQRT = 256;
export const METABALL_PARTICLES_COUNT
  = METABALL_PARTICLES_COUNT_SQRT * METABALL_PARTICLES_COUNT_SQRT;
export const METABALL_PARTICLES_SPAWN_LENGTH = 4.0;
