import { GL_ZERO, GL_ONE, GL_SRC_COLOR, GL_ONE_MINUS_SRC_COLOR, GL_DST_COLOR, GL_ONE_MINUS_DST_COLOR, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_DST_ALPHA, GL_ONE_MINUS_DST_ALPHA, GL_CONSTANT_COLOR, GL_ONE_MINUS_CONSTANT_COLOR, GL_CONSTANT_ALPHA, GL_ONE_MINUS_CONSTANT_ALPHA, GL_SRC_ALPHA_SATURATE } from './constants';

export type GLBlendFactor =
  | typeof GL_ZERO
  | typeof GL_ONE
  | typeof GL_SRC_COLOR
  | typeof GL_ONE_MINUS_SRC_COLOR
  | typeof GL_DST_COLOR
  | typeof GL_ONE_MINUS_DST_COLOR
  | typeof GL_SRC_ALPHA
  | typeof GL_ONE_MINUS_SRC_ALPHA
  | typeof GL_DST_ALPHA
  | typeof GL_ONE_MINUS_DST_ALPHA
  | typeof GL_CONSTANT_COLOR
  | typeof GL_ONE_MINUS_CONSTANT_COLOR
  | typeof GL_CONSTANT_ALPHA
  | typeof GL_ONE_MINUS_CONSTANT_ALPHA
  | typeof GL_SRC_ALPHA_SATURATE;
