import { GL_LINEAR, GL_LINEAR_MIPMAP_LINEAR, GL_LINEAR_MIPMAP_NEAREST, GL_NEAREST, GL_NEAREST_MIPMAP_LINEAR, GL_NEAREST_MIPMAP_NEAREST } from './constants';

export type GLTextureMinFilterType =
  | typeof GL_NEAREST
  | typeof GL_LINEAR
  | typeof GL_NEAREST_MIPMAP_NEAREST
  | typeof GL_LINEAR_MIPMAP_NEAREST
  | typeof GL_NEAREST_MIPMAP_LINEAR
  | typeof GL_LINEAR_MIPMAP_LINEAR;
